apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-image-task
spec:
  params:
    - name: sourceImage
      type: string
    - name: sourceTag
      type: string
    - name: destinationImage
      type: string
    - name: destinationTag
      type: string
    - name: scheduled
      type: string
      default: false
    - name: referencePolicy
      type: string
      default: source
    - name: alias
      type: string
      default: false
  steps:
    - name: tag
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      script: |
        oc tag $(params.sourceImage):$(params.sourceTag) $(params.destinationImage):$(params.destinationTag) --scheduled=$(params.scheduled) --reference-policy=$(params.referencePolicy) --alias=$(params.alias)
