name: ci-oauth-server

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "oauth-server/src/API/**"
      - ".github/workflows/ci-oauth-server.yml"

env:
  IMAGE_NAME: oauth-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: ./oauth-server/src
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
