name: promote-all-to-training

on:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
  IMAGE_CURRENT_ENV_TAG: test
  IMAGE_PROMOTE_ENV_TAG: training
  IMAGE_PROMOTE_ENV_BACKUP_TAG: training-backup

jobs:
  promote-all-images-to-test:
    name: Promote all Docker images to training
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'

    steps:
      - uses: actions/checkout@v4

      - name: Promote ess-backend
        uses: tinact/docker.image-retag@master
        with:
          image_name: ess-backend
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote oauth-server
        uses: tinact/docker.image-retag@master
        with:
          image_name: oauth-server
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote registrants-portal-api
        uses: tinact/docker.image-retag@master
        with:
          image_name: registrants-portal-api
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote registrants-portal-ui
        uses: tinact/docker.image-retag@master
        with:
          image_name: registrants-portal-ui
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote responders-portal-api
        uses: tinact/docker.image-retag@master
        with:
          image_name: responders-portal-api
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote responders-portal-ui
        uses: tinact/docker.image-retag@master
        with:
          image_name: responders-portal-ui
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote suppliers-portal-api
        uses: tinact/docker.image-retag@master
        with:
          image_name: suppliers-portal-api
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote suppliers-portal-ui
        uses: tinact/docker.image-retag@master
        with:
          image_name: suppliers-portal-ui
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
